In [8]:
import tensorflow as tf

raw_image_dataset = tf.data.TFRecordDataset('images.tfrecords')

# Create a dictionary describing the features.
image_feature_description = {
    'label': tf.io.FixedLenFeature([], tf.int64),
    'image_raw': tf.io.FixedLenFeature([], tf.string),
}

def _parse_image_function(example_proto):
  example = tf.io.parse_single_example(example_proto, image_feature_description)
  label, image = example["label"], example["image_raw"]
  print(tf.io.parse_single_example(example_proto, image_feature_description))
  # image_raw = image_features['image_raw']
  image = tf.io.decode_raw(image, tf.uint8)
  image = tf.reshape(image, [640, 240, 3])
  return {
    "label": label, 
    "image": image
    }
  
  # return tf.io.parse_single_example(example_proto, image_feature_description)

parsed_image_dataset = raw_image_dataset.map(_parse_image_function)
parsed_image_dataset

Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Constant'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
Please report this to the TensorFlow team. When filing the bug, set the verbosity to 10 (on Linux, `export AUTOGRAPH_VERBOSITY=10`) and attach the full output.
Cause: module 'gast' has no attribute 'Constant'
To silence this warning, decorate the function with @tf.autograph.experimental.do_not_convert
{'image_raw': <tf.Tensor 'ParseSingleExample_1/ParseExample/ParseExampleV2:0' shape=() dtype=string>, 'label': <tf.Tensor 'ParseSingleExample_1/ParseExample/ParseExampleV2:1' shape=() dtype=int64>}


<MapDataset shapes: {label: (), image: (640, 240, 3)}, types: {label: tf.int64, image: tf.uint8}>

In [9]:
for image_features in parsed_image_dataset:
  image = image_features['image']
  print(image)
  break

tf.Tensor(
[[[ 6  6  6]
  [ 5  5  5]
  [ 4  4  4]
  ...
  [ 8  8  8]
  [ 9  9  9]
  [ 8  8  8]]

 [[ 8  8  8]
  [ 9  9  9]
  [10 10 10]
  ...
  [ 3  3  3]
  [ 4  4  4]
  [ 3  3  3]]

 [[ 4  4  4]
  [ 5  5  5]
  [ 4  4  4]
  ...
  [ 4  4  4]
  [ 4  4  4]
  [ 4  4  4]]

 ...

 [[ 8  8  8]
  [ 5  5  5]
  [ 7  7  7]
  ...
  [ 7  7  7]
  [ 3  3  3]
  [ 5  5  5]]

 [[ 4  4  4]
  [ 5  5  5]
  [ 2  2  2]
  ...
  [26 26 26]
  [26 26 26]
  [25 25 25]]

 [[25 25 25]
  [28 28 28]
  [31 31 31]
  ...
  [25 25 25]
  [12 12 12]
  [20 20 20]]], shape=(640, 240, 3), dtype=uint8)


In [11]:
print(raw_image_dataset["image"])

AttributeError: module 'tensorflow._api.v2.train' has no attribute 'shuffle_batch'